language : python
cache : false

services :
    - mongodb
    - rabbitmq

addons:
  apt:
    sources:
    - mongodb-3.0-precise
    packages:
    - mongodb-org-server

matrix :
    include :
        - os : linux
          dist : precise
          sudo : required
          python : 3.4
        - os : linux
          dist : trusty
          sudo : required
          python : 3.4
        - os : linux
          dist : precise
          sudo : required
          python : 3.5
        - os : linux
          dist : trusty
          sudo : required
          python : 3.5

before_install :
    - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
    - chmod +x miniconda.sh
    - ./miniconda.sh -b
    - export PATH=/home/travis/miniconda2/bin:$PATH
    - conda update --yes conda
    - sudo rm -rf /dev/shm
    - sudo ln -s /run/shm /dev/shm

install :
    - sudo apt-get --yes install openssl gfortran
    - conda install --yes python=$TRAVIS_PYTHON_VERSION numpy scipy
    - pip install -r requirements.txt
    - python etc/nltk_helper.py
    - python setup.py install

before_script :
    - celery -A redicorpus worker &
    - sleep 15

script : py.test

notifications :
    email :
        recipients :
            - dillon.niederhut@gmail.com
        on_success : change
        on_failure : change
